#pragma once

#include <stddef.h>

#include "pico/stdlib.h"

#define MATRIX_ROW_COUNT 4u
#define MATRIX_COLUMN_COUNT 4u

#define MATRIX_SCAN_INTERVAL_MS 1u
#define MATRIX_DEBOUNCE_MS 8u
#define STATUS_LED_PULSE_MS 80u
#define STATUS_LED_PIN PICO_DEFAULT_LED_PIN

#define AUDIO_I2S_BCK_PIN 16u
#define AUDIO_I2S_LRCK_PIN 17u
#define AUDIO_I2S_DATA_PIN 18u
#define AUDIO_SAMPLE_RATE_HZ 48000u
#define AUDIO_BITS_PER_SAMPLE 32u
#define AUDIO_CHANNEL_COUNT 2u
#define AUDIO_TEST_TONE_HZ 50.0f

extern const uint MATRIX_ROW_PINS[MATRIX_ROW_COUNT];
extern const uint MATRIX_COLUMN_PINS[MATRIX_COLUMN_COUNT];
